### PR TITLE
[WIP] zh_CN.json Translation

### PR DESCRIPTION
**Pull request by bitUpsurge**
Dear SnailDOS,

Adding support for Chinese Simplified (China) language for Message Backup Bot.

Best Regards,
EnderPace.

### CODE REVIEW

**Comment by bitUpsurge** [comment]
Dear SnailDOS,

Translation under-progress ⟳.

Best Regards,
EnderPace.

**Comment by bitUpsurge** [comment]
Live Translation Progress Tracker,

▰▰▰▰▰▰▰▰▰▰ 100%
Note: this will be updated to current status of translation.

Best Regards,
EnderPace.

**Comment by bitUpsurge** [comment]
Dear SnailDOS,

Translation is successfully finished, you can begin pulling request.

Best Regards,
EnderPace.

**Comment by snaildos** [comment]
Thank you!

**Pull request merged**
