### PR TITLE
de_DE Translation

### PR DESCRIPTION
**Pull request by Felix-Chaos**
Full translation of the Lang file 

Need to test it if it fits 100%

### CODE REVIEW

**Review by snaildos — APPROVED** [review]
Looks all good. Will merge momentarily.

**Comment by withmask** [comment]
Hi, first of all i would like to thank you for your contribution.

However, the filename must be one of the values in the following [table](https://discord.com/developers/docs/reference#locales).

I sincerely apologize as this was my mistake before. But we changed the way how we handle locales.

I would also like to request to update the `de` translations to the latest version (From the keys on the en-US file that i will commit soon).

Thank you so much for your contribution.

This might be a burden for you, i completely understand if you don't have the time to do so. Thank you again.

**Comment by snaildos** [comment]
Yeah, this is my bad. I thought we where following language locales, not the discord version one.

**Comment by snaildos** [comment]
Just DM me on Discord and we'll work it out.

**Pull request merged**
